import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { describe, test, expect } from "./test-helpers.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export async function runBrandingTests() {
  console.log("\n📦 Running Branding & Rename Verification Tests...");

  await describe("Branding: Application Name Renamed to Grid", async () => {
    await test("Backend agent package.json specifies 'grid' as name", async () => {
      const pkgPath = path.resolve(__dirname, "../backend/services/agent/package.json");
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
      expect(pkg.name).toBe("grid");
    });

    await test("Frontend package.json specifies 'grid' as name", async () => {
      const pkgPath = path.resolve(__dirname, "../frontend/package.json");
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
      expect(pkg.name).toBe("grid");
    });

    await test("Frontend index.html title is set to Grid", async () => {
      const htmlPath = path.resolve(__dirname, "../frontend/index.html");
      const html = fs.readFileSync(htmlPath, "utf-8");
      expect(html).toContain("<title>Grid</title>");
    });

    await test("Frontend Welcome heading in Home.jsx is 'Welcome to Grid'", async () => {
      const homePath = path.resolve(__dirname, "../frontend/src/pages/Home.jsx");
      const homeContent = fs.readFileSync(homePath, "utf-8");
      expect(homeContent).toContain("Welcome to Grid");
    });

    await test("Frontend Sidebar header displays Grid", async () => {
      const sidebarPath = path.resolve(__dirname, "../frontend/src/components/Sidebar.jsx");
      const content = fs.readFileSync(sidebarPath, "utf-8");
      expect(content).toContain('>Grid</span>');
    });

    await test("Frontend MessageList displays Grid", async () => {
      const msgListPath = path.resolve(__dirname, "../frontend/src/components/MessageList.jsx");
      const content = fs.readFileSync(msgListPath, "utf-8");
      expect(content).toContain('>Grid</h1>');
    });

    await test("Frontend ChatInput placeholders reference Grid", async () => {
      const chatInputPath = path.resolve(__dirname, "../frontend/src/components/ChatInput.jsx");
      const content = fs.readFileSync(chatInputPath, "utf-8");
      expect(content).toContain('auto:"Ask Grid..."');
      expect(content).toContain('chat:"Chat with Grid..."');
      expect(content).toContain("Grid can make mistakes. Verify important info.");
    });

    await test("Frontend BillingDrawer references Grid", async () => {
      const billingDrawerPath = path.resolve(__dirname, "../frontend/src/components/BillingDrawer.jsx");
      const content = fs.readFileSync(billingDrawerPath, "utf-8");
      expect(content).toContain('name: "Grid"');
    });

    await test("Backend agent prompts reference Grid instead of legacy name", async () => {
      const chatAgent = fs.readFileSync(path.resolve(__dirname, "../backend/services/agent/agents/chat.agent.js"), "utf-8");
      expect(chatAgent).toContain("You are Grid, an intelligent AI assistant.");

      const codingAgent = fs.readFileSync(path.resolve(__dirname, "../backend/services/agent/agents/coding.agent.js"), "utf-8");
      expect(codingAgent).toContain("You are Grid Coding Agent.");

      const pdfAgent = fs.readFileSync(path.resolve(__dirname, "../backend/services/agent/agents/pdf.agent.js"), "utf-8");
      expect(pdfAgent).toContain('Author: "Grid"');
      expect(pdfAgent).toContain('Creator: "Grid PDF Agent"');
      expect(pdfAgent).toContain('"Generated by Grid"');

      const pdfRagAgent = fs.readFileSync(path.resolve(__dirname, "../backend/services/agent/agents/pdfRag.agent.js"), "utf-8");
      expect(pdfRagAgent).toContain("You are Grid PDF Assistant.");

      const pptAgent = fs.readFileSync(path.resolve(__dirname, "../backend/services/agent/agents/ppt.agent.js"), "utf-8");
      expect(pptAgent).toContain('ppt.author  = "Grid"');
      expect(pptAgent).toContain('"Generated by Grid"');

      const visionAgent = fs.readFileSync(path.resolve(__dirname, "../backend/services/agent/agents/vision.agent.js"), "utf-8");
      expect(visionAgent).toContain("You are Grid Vision Agent.");
    });

    await test("Zero occurrences of 'cortex' exist in source files", async () => {
      const filesToCheck = [
        "../backend/services/agent/package.json",
        "../backend/services/agent/agents/chat.agent.js",
        "../backend/services/agent/agents/coding.agent.js",
        "../backend/services/agent/agents/pdf.agent.js",
        "../backend/services/agent/agents/pdfRag.agent.js",
        "../backend/services/agent/agents/ppt.agent.js",
        "../backend/services/agent/agents/vision.agent.js",
        "../frontend/package.json",
        "../frontend/index.html",
        "../frontend/src/pages/Home.jsx",
        "../frontend/src/components/Sidebar.jsx",
        "../frontend/src/components/MessageList.jsx",
        "../frontend/src/components/ChatInput.jsx",
        "../frontend/src/components/BillingDrawer.jsx"
      ];

      for (const rel of filesToCheck) {
        const fullPath = path.resolve(__dirname, rel);
        const text = fs.readFileSync(fullPath, "utf-8");
        const hasCortex = /cortex/i.test(text);
        if (hasCortex) {
          throw new Error(`Found unexpected cortex reference in ${rel}`);
        }
        expect(hasCortex).toBeFalsy();
      }
    });
  });
}
